### ISSUE TITLE
file do not emit at the first build when using cache-loader with file-loader

### ISSUE THREAD

**Issue by Akiq2016** [webpack-contrib/cache-loader#112]
same question as https://github.com/webpack-contrib/cache-loader/issues/82

- Operating System: macOS 10.15.6
- Node Version: v12.18.3
- NPM Version: 6.14.6
- webpack Version: 5.2.0
- webpack-cli Version: 4.1.0
- cache-loader Version: 4.1.0

### How Do We Reproduce?

demo: https://github.com/Akiq2016/test-cache-loader

**Comment by evilebottnawi** [comment]
> webpack Version: 5.2.0

Don't use this loader for webpack@5 , please migrate https://webpack.js.org/configuration/other-options/#cache, time to deprecated this loader
