### ISSUE TITLE
Phrasing "in front of" confusing?

### ISSUE THREAD

**Issue by peteruithoven** [webpack-contrib/cache-loader#12]
The cache-loader readme mentions that the cache-loader needs to be added in front of other loaders: 
> Add this loader in front of other (expensive) loaders to cache the result on disk.

I find the phrasing "in front of" confusing, since the loaders are used right from left / last to first ([use docs](https://webpack.js.org/configuration/module/#rule-use)). So Looking at the code examples they should be used last, but added in front of the use configuration?

**Comment by jintoppy** [comment]
I think this is still valid. If the cache-loader to take effect, shouldn't this be added on the right rather than at the left most? How that will work?
