### ISSUE TITLE
.cache-loader file make mistake

### ISSUE THREAD

**Issue by SnowFlowers** [webpack-contrib/cache-loader#13]
i use git for my project . when i checkout one branch to another. it got error in my npm start. but when i  deleted this file, i restarted successfully.  what can i do?

**Comment by evilebottnawi** [comment]
@SnowFlowers What error do you get?

**Comment by evilebottnawi** [comment]
@SnowFlowers also you don't commit .cache-loader file

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions :)
