### ISSUE TITLE
Less output not getting updated

### ISSUE THREAD

**Issue by kfeinUI** [webpack-contrib/cache-loader#14]
**cache-loader version:** 1.0.3

**Relevant rule:** 
```
{
   test: /\.less$/,
   use: extractStyles.extract([
       'cache-loader',
       'css-loader',
      'less-loader'
   ])
}
```

Just added cache-loader and am finding that the output of my project less files doesn't get updated. Ran into it on multiple machines. No errors reported. It must not be invalidating the cache appropriately in this case. Works fine with JS and TS.

**Comment by evilebottnawi** [comment]
@kfeinUI can your provide minimum reproducible test repo, maybe problem in `less-loader`

**Comment by michael-ciniawsky** [comment]
Could you try without `extract-text-webpack-plugin` aswell please

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions :)
