### ISSUE TITLE
Unable to be used in CI

### ISSUE THREAD

**Issue by juanca** [webpack-contrib/cache-loader#29]
See original comment @ 
https://github.com/webpack-contrib/cache-loader/commit/070af07cd54c1fd7da4bed3449f1a65cdbc7103e#r26826081

Looks like there is some timestamp-fu that is not allowing the `.cache-loader/` folder to be cached across VMs.

**Comment by juanca** [comment]
I think I'm understanding why it doesn't work in CI:

When a CI container pulls in the codebase, each of those files gets an up-to-date modified time (`mtime`). 

However, the `.cache-loader` files have stored an `mtime` of the last build.

**Comment by juanca** [comment]
I'm closing this issue since it looks like this is done by design. I would be open to improving the caching mechanism. Let me know if y'all are also open to that idea.

**Comment by eranshapira** [comment]
The fact that I can't use this loader in my CI is very disappointing. I could be using that to decrease build time from 5m to 30secs...
