### ISSUE TITLE
Question: Is cache invalidated when webpack config changes?

### ISSUE THREAD

**Issue by amilajack** [webpack-contrib/cache-loader#38]

**Comment by evilebottnawi** [comment]
@amilajack node, it is not required

**Comment by amilajack** [comment]
Okay. Because I changed my webpack config and noticed that i was still getting the results of the previous config

**Comment by michael-ciniawsky** [comment]
If you change the config of one of the loaders in the loaders chain where the `cache-loader` is applied you need to manually purge the cache for that `cache-loader` invocation
