### ISSUE TITLE
Change default cache directory

### ISSUE THREAD

**Issue by stevenvachon** [webpack-contrib/cache-loader#62]
* Operating System: macOS 10.14.3
* Node Version: 10.15.2
* NPM Version: 6.4.1
* webpack Version: 4.29.5
* cache-loader Version: 2.0.1

### Feature Proposal
Instead of `./cache-loader`, it should be `./node_modules/.cache/cache-loader`

### Feature Use Case
Consistent with other loaders and to avoid a specific gitignore.

**Comment by evilebottnawi** [comment]
Yep, feel free to send a PR
