### ISSUE TITLE
Should cache-loader use `module.exports.raw = true` to handle binary file ?

### ISSUE THREAD

**Issue by malash** [webpack-contrib/cache-loader#68]
* Operating System: MacOS
* Node Version: 11.0.0
* NPM Version: 6.9.0
* webpack Version: 4.30.0
* cache-loader Version: 2.0.1

### Expected Behavior

```js
// webpack.config.js
const path = require("path");

module.exports = {
  mode: "development",
  entry: "./src/index.js",
  output: {
    path: path.join(__dirname, "dist"),
    filename: "index.js"
  },
  module: {
    rules: [
      {
        test: /\.png$/,
        use: ["file-loader", "cache-loader"]
      }
    ]
  }
};
```

```js
// index.js
import png from "./index.png";

console.log(png);
```

In this case. The `.png` is broken because `cache-loader` is not a [raw loader](https://webpack.js.org/api/loaders/#raw-loader). Which means the `source` is an UTF-8 `string` instead of `Buffer`. The binary data will be broken during conversion processed.

Some loaders, e.g. `file-loader`, [added `module.exports.raw = true`](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L55) to solved this issue.

### Actual Behavior

`.png` file broken.

### How Do We Reproduce?

cc: @Jimexist

**Comment by mistic** [comment]
@malash thanks for the report! Do you think you can provide a small example repo where I can reproduce the error and play with a solution?

**Comment by mistic** [comment]
@malash could you try with that PR https://github.com/webpack-contrib/cache-loader/pull/69 if it fixes your issue?

**Comment by malash** [comment]
Thanks @mistic . 

I'v testes the `export const raw = true` and it works for my case.

1. Should we handle buffer stringify manually ? `JSON.stringify` would convert buffer to object but `JSON.parse` won't restore it.

![image](https://user-images.githubusercontent.com/1812118/56333959-f3042780-61c8-11e9-94c9-8eaa3a468216.png)

2. Should we encode the buffer before writing cache file to reduce the cache file size ?

**Comment by mistic** [comment]
@malash thanks for the suggestions. I've fixed the JSON.stringify & JSON.parse problems and buffers are also now encoded in base64. You can test it with the last changes on https://github.com/webpack-contrib/cache-loader/pull/69

**Comment by malash** [comment]
Cool. Great work.
