### ISSUE TITLE
Control `cacheDirectory` with env variable

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [webpack-contrib/cache-loader#91]
### Feature Proposal

Add an option to control the `cacheDirectory` with an env variable (e.g. `CACHE_LOADER_CACHE_DIR`). 

### Feature Use Case

Useful for keeping the default for local dev environment and controlling the value on CI/CD.

The `cacheDirectory`option should still take precedence if specified.

**Comment by tomasz-sodzawiczny** [comment]
Implementation proposal in https://github.com/webpack-contrib/cache-loader/pull/92

**Comment by EECOLOR** [comment]
Why not just do the following in your webpack config?

```js
cacheDirectory = process.env.CACHE_LOADER_CACHE_DIR
```

**Comment by evilebottnawi** [comment]
Implemented in `find-cache-dir`
